package domain

import "errors"

var (
	ErrWorkspaceNotFound = errors.New("workspace not found")
	ErrInvalidInput = errors.New("invalid input")
	ErrWorkspacePeriodNotFound = errors.New("period not found")
	ErrWorkspacePeriodClosed = errors.New("period is closed")
	ErrWorkspaceInscriptionClosed = errors.New("period inscription is closed")
	ErrWorkspaceUserNotFound = errors.New("user not found")
	ErrWorkspaceUserNotProfessor = errors.New("user must have professor role")
	ErrWorkspaceClosedUpdateForbidden = errors.New("workspace cannot be updated because it is closed")
	ErrWorkspaceUserIDChangeNotAllowed = errors.New("workspace user_id cannot be changed")
	ErrWorkspaceNameRequired = errors.New("workspace name is required")
	ErrWorkspaceNameTooLong  = errors.New("workspace name is too long")
	ErrWorkspacePeriodIDRequired = errors.New("workspace period_id is required")
	ErrWorkspaceUserIDRequired   = errors.New("workspace user_id is required")
	ErrWorkspaceTypeRequired = errors.New("workspace type is required")
	ErrWorkspaceTypeInvalid  = errors.New("workspace type is invalid. The types allowed are: "+ValidWorkspaceTypesString())
	ErrWorkspaceInitialDateRequired   = errors.New("workspace initial_date is required")
	ErrWorkspaceInitialDateWrongFormat  = errors.New("workspace initial_date has wrong format (expected YYYY-MM-DD)")
	ErrWorkspaceFinalDateRequired      = errors.New("workspace final_date is required")
	ErrWorkspaceFinalDateWrongFormat   = errors.New("workspace final_date has wrong format (expected YYYY-MM-DD)")
	ErrWorkspaceDateSequenceInvalid    = errors.New("workspace initial_date must be before final_date")
	ErrWorkspaceInitialDateOutOfRange = errors.New("workspace initial_date must be within the period date range")
	ErrWorkspaceFinalDateOutOfRange   = errors.New("workspace final_date must be within the period date range")
	ErrWorkspaceStateRequired = errors.New("workspace state is required")
	ErrWorkspaceStateInvalid  = errors.New("workspace state is invalid. The states allowed are: "+ValidWorkspaceStatesString())
)
