sonar.projectKey=Desarrollo-de-Soluciones-Cloud_202612-MISW4204-Grupo13_d9216313-c4a5-4c1d-899d-b099d39e6e30
sonar.go.coverage.reportPaths=backend/coverage.out
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.exclusions=k6-tests/**,frontend/node_modules/**,frontend/dist/**,frontend/coverage/**
sonar.coverage.exclusions=backend/cmd/**,backend/internal/**/test/**,backend/internal/**/*_test.go,frontend/src/main.tsx,frontend/src/vite-env.d.ts,frontend/src/api/types.ts,frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx,frontend/src/**/__tests__/**,frontend/src/test/**
