sonar.projectKey=Desarrollo-de-Soluciones-Cloud_202612-MISW4204-Grupo13_d9216313-c4a5-4c1d-899d-b099d39e6e30
sonar.go.coverage.reportPaths=backend/coverage.out
sonar.coverage.exclusions=backend/cmd/**,backend/internal/**/test/**,backend/internal/**/*_test.go
sonar.exclusions=k6-tests/**